name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    types: [opened, synchronize]

jobs:
  build:
    name: Build and Test
    timeout-minutes: 15
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3
        with:
          fetch-depth: 2

      - uses: pnpm/action-setup@v2.0.1
        with:
          version: 6.32.2

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
      - name: Deploy to surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "joaoguilherme.surge.sh"
          project: "../../apps/IMDb-best_season/dist/"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
      - name: Deploy to surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "joaoguilherme2.surge.sh"
          project: "../../apps/j.me/dist/"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
      - name: Deploy to surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "joaoguilherme3.surge.sh"
          project: "../../apps/spotify-popularity/dist/"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
      - name: Deploy to surge.sh
        uses: dswistowski/surge-sh-action@v1
        with:
          domain: "joaoguilherme4.surge.sh"
          project: "../../apps/IMDb-best_season/youtube/dist/"
          login: ${{ secrets.surge_login }}
          token: ${{ secrets.surge_token }}
